services:
  - type: web
    name: nestjs-tutorial
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: node --max-old-space-size=512 dist/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=512